//Screen dimension constants
const double RAZON=1.5;
const int barra=RAZON*70;
const int SCREEN_WIDTH=RAZON*480;
const int SCREEN_HEIGHT=RAZON*480+barra;  //Matriz sería de 480x480

//Key press surfaces constants
enum KeyPressSurfaces
{
	PERSONAJE,              //0
	PERSONAJE_INMORTAL,
	PERSONAJE_INMORTAL_ESPADA,
	PERSONAJE_INMORTAL_ESCUDO,
	PERSONAJE_ESPADA,
	PERSONAJE_ESCUDO,
	INMORTALIDAD,           //14
	FONDO,
	DANO_1,
	DANO_2,
	DANO_3,
	MURO,                   //6
	OBJETIVO,               //5
	VIDA,
	VIDA_GRIS,
	PENALIZACION,
	NO_VIDA,
	BORDE_VIDA,
	ESTAMINA_1,
	ESTAMINA_2,
	NO_ESTAMINA,
	MANA_AUX,
	CERRADURA,              //7
	CERRADURA_DOBLE,        //11
	LLAVE,                  //8
	ICONO_LLAVE,
	ICONO_VENENO,
    ICONO_VENENO2,
	ICONO_REGEN,
	ICONO_REGEN2,
	ICONO_NOREGEN,
	BARRA_MANA,
	G_CONTADOR,
	G_CONTADORMAX,
	CURACION,
	BOLA,                   //10
	AGUJERO,                //12
	AGUJERO_RELLENO,        //13
	PLACA_PRESION,          //15
	PLACA_AVERIADA,         //23
	BARRA_ARRIBA,           //16
	BARRA_ABAJO,            //17
	MARCA,
	NO_MARCA,
	ROCA_ARRIBA,            //18
	ROCA_ABAJO,             //19
	ROCA_IZQUIERDA,         //20
	ROCA_DERECHA,           //21
	POLVO,                  //22
	PLANTA_VENENO,          //24
	PLANTA_VENENO_ROTA,     //25
	MANA,                   //26
	ESQUELETO_VIDAALTA,     //50
	ESQUELETO_VIDAMEDIA,    //51
	ESQUELETO_VIDABAJA,     //52
	ESQUELETO_MUERTO,       //53
	ESQUELETO_VIDAALTA_ATACANDO,     //54
	HUESO,                  //55
	ESQUELETO_VIDAALTA_ANTESDEATACAR,   //56
	ESQUELETO_VIDAMEDIA_ATACANDO,       //57
	ESQUELETO_VIDAMEDIA_ANTESDEATACAR,  //58
	ESQUELETO_VIDABAJA_ATACANDO,        //59
	ESQUELETO_VIDABAJA_ANTESDEATACAR,   //60
	ESQUELETO_VIDAALTA_ATURDIDO,        //61
	ESQUELETO_VIDAMEDIA_ATURDIDO,       //62
	ESQUELETO_VIDABAJA_ATURDIDO,        //63
	KEY_PRESS_SURFACE_TOTAL
};
